Repository MARU-EGG/MARU_EGG_BE, pull requests merged in 2025-02, with the labels that each got.

#97 [MARU-19] refactor: nginx.conf 파일 ci - cd 자동 배포
  .github/workflows/ci-cd.yml
  src/main/java/mju/iphak/maru_egg/auth/application/AuthService.java
Labels: 🌏인프라

#98 [MARU-37] fix : front 작업 url cors 추가
  nginx/conf.d/nginx.conf
Labels: 🎯리팩토링

#99 [MARU-38] fix : nginx.conf 파일 변경사항 적용 디버깅 적용
  .github/workflows/ci-cd.yml
Labels: 🌏인프라

#100 [MARU-39] fix : nginx.conf 파일 변경사항 적용 test 적용
  nginx/conf.d/nginx.conf
Labels: 🎯리팩토링

#102 [MARU-41] fix : nginx.conf 파일 변경사항 적용 및 ci/cd 스크립트 수정
  .github/workflows/ci-cd.yml
  nginx/conf.d/nginx.conf
Labels: 🌏인프라

#104 fix : ci cd nginx 스크립트 수정
  .github/workflows/ci-cd.yml
  nginx/conf.d/nginx.conf
Labels: 🌏인프라

#105 [MARU-42] feat : 캠퍼스/단과대/학과 crud
  src/main/java/mju/iphak/maru_egg/campus/api/CollegeController.java
  src/main/java/mju/iphak/maru_egg/campus/api/DepartmentController.java
  src/main/java/mju/iphak/maru_egg/campus/api/admin/AdminCollegeController.java
  src/main/java/mju/iphak/maru_egg/campus/api/admin/AdminDepartmentController.java
  src/main/java/mju/iphak/maru_egg/campus/api/dto/request/CreateCollegeRequest.java
  src/main/java/mju/iphak/maru_egg/campus/api/dto/request/CreateDepartmentRequest.java
  src/main/java/mju/iphak/maru_egg/campus/api/dto/request/UpdateCollegeRequest.java
  src/main/java/mju/iphak/maru_egg/campus/api/dto/request/UpdateDepartmentRequest.java
  src/main/java/mju/iphak/maru_egg/campus/api/dto/response/CollegeResponse.java
  src/main/java/mju/iphak/maru_egg/campus/api/dto/response/DepartmentResponse.java
  src/main/java/mju/iphak/maru_egg/campus/api/swagger/AdminCollegeControllerDocs.java
  src/main/java/mju/iphak/maru_egg/campus/api/swagger/AdminDepartmentControllerDocs.java
  src/main/java/mju/iphak/maru_egg/campus/api/swagger/CollegeControllerDocs.java
  src/main/java/mju/iphak/maru_egg/campus/api/swagger/DepartmentControllerDocs.java
  src/main/java/mju/iphak/maru_egg/campus/application/college/command/create/CreateCollege.java
  src/main/java/mju/iphak/maru_egg/campus/application/college/command/create/CreateCollegeService.java
  src/main/java/mju/iphak/maru_egg/campus/application/college/command/delete/DeleteCollege.java
  src/main/java/mju/iphak/maru_egg/campus/application/college/command/delete/DeleteCollegeService.java
  src/main/java/mju/iphak/maru_egg/campus/application/college/command/update/UpdateCollege.java
  src/main/java/mju/iphak/maru_egg/campus/application/college/command/update/UpdateCollegeService.java
  src/main/java/mju/iphak/maru_egg/campus/application/college/query/find/FindAllByCampusType.java
  src/main/java/mju/iphak/maru_egg/campus/application/college/query/find/FindAllByCampusTypeService.java
  src/main/java/mju/iphak/maru_egg/campus/application/college/query/find/FindAllCollege.java
  src/main/java/mju/iphak/maru_egg/campus/application/college/query/find/FindAllCollegeService.java
  src/main/java/mju/iphak/maru_egg/campus/application/department/command/create/CreateDepartment.java
  src/main/java/mju/iphak/maru_egg/campus/application/department/command/create/CreateDepartmentService.java
  src/main/java/mju/iphak/maru_egg/campus/application/department/command/delete/DeleteDepartment.java
  src/main/java/mju/iphak/maru_egg/campus/application/department/command/delete/DeleteDepartmentService.java
  src/main/java/mju/iphak/maru_egg/campus/application/department/command/update/UpdateDepartment.java
  src/main/java/mju/iphak/maru_egg/campus/application/department/command/update/UpdateDepartmentService.java
  src/main/java/mju/iphak/maru_egg/campus/application/department/query/FindAllByCollege.java
  src/main/java/mju/iphak/maru_egg/campus/application/department/query/FindAllByCollegeService.java
  src/main/java/mju/iphak/maru_egg/campus/application/department/query/FindAllDepartment.java
  src/main/java/mju/iphak/maru_egg/campus/application/department/query/FindAllDepartmentService.java
  src/main/java/mju/iphak/maru_egg/campus/domain/CampusType.java
  src/main/java/mju/iphak/maru_egg/campus/domain/College.java
  src/main/java/mju/iphak/maru_egg/campus/domain/Department.java
  src/main/java/mju/iphak/maru_egg/campus/repository/CollegeRepository.java
  src/main/java/mju/iphak/maru_egg/campus/repository/DepartmentRepository.java
  src/main/java/mju/iphak/maru_egg/common/config/SecurityConfig.java
  src/main/java/mju/iphak/maru_egg/common/exception/ErrorCode.java
  src/test/java/mju/iphak/maru_egg/answerreference/domain/AnswerReferenceTest.java
  src/test/java/mju/iphak/maru_egg/campus/api/CollegeControllerTest.java
  src/test/java/mju/iphak/maru_egg/campus/api/DepartmentControllerTest.java
  src/test/java/mju/iphak/maru_egg/campus/api/admin/AdminCollegeControllerTest.java
  src/test/java/mju/iphak/maru_egg/campus/api/admin/AdminDepartmentControllerTest.java
  src/test/java/mju/iphak/maru_egg/campus/application/college/command/create/CreateCollegeServiceTest.java
  src/test/java/mju/iphak/maru_egg/campus/application/college/command/delete/DeleteCollegeServiceTest.java
  src/test/java/mju/iphak/maru_egg/campus/application/college/command/update/UpdateCollegeServiceTest.java
  src/test/java/mju/iphak/maru_egg/campus/application/college/query/find/FindAllByCampusTypeServiceTest.java
  src/test/java/mju/iphak/maru_egg/campus/application/college/query/find/FindAllCollegeServiceTest.java
  src/test/java/mju/iphak/maru_egg/campus/application/department/command/create/CreateDepartmentServiceTest.java
  src/test/java/mju/iphak/maru_egg/campus/application/department/command/delete/DeleteDepartmentServiceTest.java
  src/test/java/mju/iphak/maru_egg/campus/application/department/command/update/UpdateDepartmentServiceTest.java
  src/test/java/mju/iphak/maru_egg/campus/application/department/query/FindAllByCollegeServiceTest.java
  src/test/java/mju/iphak/maru_egg/campus/application/department/query/FindAllDepartmentServiceTest.java
Labels: 🧪테스트, ✨기능
